// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Surface_Entities.Context;

#nullable disable

namespace Surface_DataAccessLayer.Migrations
{
    [DbContext(typeof(SurfaceContext))]
    [Migration("20230825102338_init1")]
    partial class init1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Surface.Entities.DataModels.StatusGroup", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StatusGroups");

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            CreatedOn = new DateTime(2023, 8, 25, 15, 53, 38, 200, DateTimeKind.Local).AddTicks(5317),
                            ModifiedOn = new DateTime(2023, 8, 25, 15, 53, 38, 200, DateTimeKind.Local).AddTicks(5327),
                            Name = "User"
                        },
                        new
                        {
                            Id = (byte)2,
                            CreatedOn = new DateTime(2023, 8, 25, 15, 53, 38, 200, DateTimeKind.Local).AddTicks(5329),
                            ModifiedOn = new DateTime(2023, 8, 25, 15, 53, 38, 200, DateTimeKind.Local).AddTicks(5330),
                            Name = "Project"
                        },
                        new
                        {
                            Id = (byte)3,
                            CreatedOn = new DateTime(2023, 8, 25, 15, 53, 38, 200, DateTimeKind.Local).AddTicks(5331),
                            ModifiedOn = new DateTime(2023, 8, 25, 15, 53, 38, 200, DateTimeKind.Local).AddTicks(5332),
                            Name = "Task"
                        },
                        new
                        {
                            Id = (byte)4,
                            CreatedOn = new DateTime(2023, 8, 25, 15, 53, 38, 200, DateTimeKind.Local).AddTicks(5333),
                            ModifiedOn = new DateTime(2023, 8, 25, 15, 53, 38, 200, DateTimeKind.Local).AddTicks(5334),
                            Name = "Feature"
                        },
                        new
                        {
                            Id = (byte)5,
                            CreatedOn = new DateTime(2023, 8, 25, 15, 53, 38, 200, DateTimeKind.Local).AddTicks(5335),
                            ModifiedOn = new DateTime(2023, 8, 25, 15, 53, 38, 200, DateTimeKind.Local).AddTicks(5335),
                            Name = "Bug"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
